# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  workflow_call:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: build
      run: |
        cd  src
        cd RSCG_InterceptorTemplate
        dotnet restore
        dotnet tool restore
        dotnet r pack

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: RSCG_InterceptorTemplate_NuGetPackage
        path: 'src/RSCG_InterceptorTemplate/Packages/*'
        retention-days: 1
