name: Deploy Nuget

on:
  workflow_dispatch:
  
jobs:
  mainBuild:
    uses: ./.github/workflows/build.yml 
  build:
    needs: [mainBuild]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: RSCG_InterceptorTemplate_NuGetPackage
          path: src

      - name: publish nuget
        run: |
          cd src
          ls -lh

      - name: push nuget
        run: |
          dotnet nuget push ${{github.workspace}}/src/*symb*.*pkg --api-key  ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json
    